### ISSUE TITLE
Feature request: implement batch / createKeyStream / createValueStream

### ISSUE THREAD

**Issue by alessioalex** [juliangruber/level-prefix#2]
It would be really nice to have `db.batch` as well, otherwise this might cause problems with other level\* modules. And it's a nice to have too.

I'll try to get a swing at this myself. / cc @juliangruber

**Comment by juliangruber** [comment]
I totally forgot about that :D

**Comment by alessioalex** [comment]
No worries, I'll make it happen.

Btw I also think createKeyStream should be supported, to maintain compatibility with the levelUp API.

**Comment by juliangruber** [comment]
yes, and createValueStream
