### ISSUE TITLE
createWriteStream() doesn't work

### ISSUE THREAD

**Issue by alessioalex** [juliangruber/level-prefix#7]
While writing the tests for this I found out it doesn't work.

I'm on it :8ball:

**Comment by alessioalex** [comment]
Fixed in 456c5216087e75ff7b8c2c7393ea8f98173f42db

**Comment by alessioalex** [comment]
@juliangruber maybe you can bump the version if everything's ok with you ( btw also added `readable-stream` for backwards compatibility with Node 0.8.x )

**Comment by juliangruber** [comment]
sweet, published as 0.1.1!
